import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Bot, Sparkles, FileText, ListChecks, ChevronRight, ChevronLeft,
  Copy, Check, Loader, Users, ClipboardList, Zap, CheckCircle,
} from 'lucide-react'
import api from '../api/client'
import { renderMarkdown } from '../lib/markdown'

// ── Types ─────────────────────────────────────────────────────
interface MomData {
  title?: string
  introduction?: string
  points_discussed?: string[]
  action_items?: Array<{ task: string; owner: string; deadline: string }>
  conclusion?: string
  participants?: string[]
  date?: string
}

interface Props {
  recordingId: string | null
  summary?: string
  shortSummary?: string
  detailedSummary?: string
  keyPoints?: string[]
  actionItems?: string[]
  speakerSummary?: Record<string, { summary: string; key_points: string[]; action_items: string[] }> | null
  /** MoM data auto-generated by pipeline — shown as the primary content */
  momData?: MomData | null
  isOpen: boolean
  onToggle: () => void
  /** True while AI insights are being generated */
  isGenerating?: boolean
  /** True while MoM is still being generated (pipeline phase 2) */
  isGeneratingMom?: boolean
  /** Callback when the user clicks "Generate AI Insights" */
  onGenerateInsights?: (tasks: string[]) => void
  /** True while the on-demand AI insight generation is running */
  isGeneratingInsights?: boolean
}

// ── Proper Markdown renderer using the lib ───────────────────
function MarkdownContent({ content, className }: { content: string; className?: string }) {
  return (
    <div
      className={`prose-ai ${className ?? ''}`}
      dangerouslySetInnerHTML={{ __html: renderMarkdown(content) }}
    />
  )
}

function LocalAIBadge() {
  return (
    <span style={{
      display: 'inline-flex', alignItems: 'center', gap: '3px',
      fontSize: '.58rem', fontWeight: 700,
      background: 'hsl(var(--success) / .12)',
      color: 'hsl(var(--success))',
      border: '1px solid hsl(var(--success) / .3)',
      borderRadius: '4px', padding: '.05rem .32rem',
      letterSpacing: '.06em', textTransform: 'uppercase',
    }}>
      <Bot size={8} /> Local AI
    </span>
  )
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false)
  const copy = () => {
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 1800)
  }
  return (
    <button
      onClick={copy}
      title="Copy"
      style={{
        background: 'none', border: 'none', cursor: 'pointer',
        color: 'hsl(var(--pencil))', padding: '3px 6px', borderRadius: '5px',
        display: 'flex', alignItems: 'center', gap: '4px',
        fontSize: '.68rem', fontFamily: 'Inter, sans-serif',
        transition: 'all .2s', opacity: 0.55,
      }}
      onMouseEnter={(e) => { const el = e.currentTarget as HTMLButtonElement; el.style.opacity = '1'; el.style.background = 'hsl(var(--muted))' }}
      onMouseLeave={(e) => { const el = e.currentTarget as HTMLButtonElement; el.style.opacity = '0.55'; el.style.background = 'none' }}
    >
      <span style={{ display: 'inline-block', transition: 'transform .2s', transform: copied ? 'rotateY(180deg)' : 'rotateY(0deg)' }}>
        {copied ? <Check size={11} style={{ color: 'hsl(var(--success))' }} /> : <Copy size={11} />}
      </span>
      {copied ? 'Copied!' : 'Copy'}
    </button>
  )
}

// ── Generating skeleton ───────────────────────────────────────
const GENERATING_MESSAGES = [
  'Analyzing transcript…',
  'Generating AI insights…',
  'Creating summary…',
  'Extracting key points…',
  'Identifying action items…',
  'Almost there…',
]

const MOM_GENERATING_MESSAGES = [
  'Analyzing meeting transcript…',
  'Drafting introduction…',
  'Identifying discussion points…',
  'Extracting action items…',
  'Writing conclusion…',
  'Finalizing minutes…',
]

function AIGeneratingSkeleton({ messages = GENERATING_MESSAGES }: { messages?: string[] }) {
  const [msgIdx, setMsgIdx] = useState(0)
  useEffect(() => {
    const t = setInterval(() => setMsgIdx(i => (i + 1) % messages.length), 2200)
    return () => clearInterval(t)
  }, [messages])
  return (
    <div style={{ padding: '1.25rem 1rem', display: 'flex', flexDirection: 'column', gap: '16px' }}>
      <div style={{
        display: 'flex', alignItems: 'center', gap: '10px',
        padding: '.7rem .9rem',
        background: 'hsl(var(--accent) / .07)',
        borderRadius: '10px',
        border: '1px solid hsl(var(--accent) / .18)',
      }}>
        <Loader size={14} className="spin" style={{ color: 'hsl(var(--accent))', flexShrink: 0 }} />
        <span style={{ fontSize: '.78rem', fontFamily: 'Inter, sans-serif', color: 'hsl(var(--accent))', fontWeight: 600 }}>
          {messages[msgIdx]}
        </span>
      </div>
      {[{ w: '100%', h: 14 }, { w: '88%', h: 14 }, { w: '95%', h: 14 }, { w: '72%', h: 14 }].map((s, i) => (
        <div key={i} style={{
          height: `${s.h}px`, width: s.w, borderRadius: '6px',
          background: 'linear-gradient(90deg, hsl(var(--muted)) 0%, hsl(var(--card)) 50%, hsl(var(--muted)) 100%)',
          backgroundSize: '200% 100%', animation: `shimmer 1.8s ease-in-out infinite`, animationDelay: `${i * 0.15}s`,
        }} />
      ))}
      <div style={{ display: 'flex', gap: '8px', marginTop: '4px' }}>
        {[60, 45, 55].map((w, i) => (
          <div key={i} style={{
            height: '28px', width: `${w}%`, borderRadius: '6px',
            background: 'linear-gradient(90deg, hsl(var(--muted)) 0%, hsl(var(--card)) 50%, hsl(var(--muted)) 100%)',
            backgroundSize: '200% 100%', animation: `shimmer 1.8s ease-in-out infinite`, animationDelay: `${i * 0.2 + 0.6}s`,
          }} />
        ))}
      </div>
      <p style={{ fontSize: '.67rem', fontFamily: 'Inter, sans-serif', color: 'hsl(var(--pencil))', textAlign: 'center', marginTop: '8px', letterSpacing: '.03em' }}>
        Qwen-AI · Running locally · Please wait
      </p>
    </div>
  )
}

// ── MoM Section renderer ──────────────────────────────────────
function MomDisplay({ mom, recordingId }: { mom: MomData; recordingId: string }) {
  const navigate = useNavigate()
  const [pdfStatus, setPdfStatus] = useState<'idle' | 'loading' | 'success' | 'error'>('idle')

  const handlePdf = async () => {
    setPdfStatus('loading')
    try {
      const res = await api.post(`/mom/${recordingId}/pdf`, {}, { responseType: 'blob' })
      const blob = new Blob([res.data], { type: 'application/pdf' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `MoM_${mom?.title?.replace(/\s+/g, '_') || 'Meeting'}.pdf`
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      URL.revokeObjectURL(url)
      setPdfStatus('success')
      setTimeout(() => setPdfStatus('idle'), 2500)
    } catch (err: unknown) {
      console.error('[MoMPdf] Failed:', err)
      setPdfStatus('error')
      setTimeout(() => setPdfStatus('idle'), 3000)
    }
  }
  
  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '12px', padding: '.9rem 1rem' }}>
 
      {/* View & Download buttons */}
      <div style={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        padding: '.5rem .75rem',
        background: 'hsl(var(--paper) / .4)',
        border: '1.5px solid hsl(var(--border) / .15)',
        borderRadius: '10px',
        marginBottom: '4px',
        gap: '10px',
      }}>
        <button
          onClick={() => navigate(`/dashboard/history/${recordingId}/mom`)}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: '6px',
            background: 'transparent',
            border: '1.5px solid hsl(var(--accent) / .4)',
            borderRadius: '6px',
            padding: '.35rem .75rem',
            fontSize: '.76rem',
            fontWeight: 600,
            color: 'hsl(var(--accent))',
            cursor: 'pointer',
            fontFamily: 'Inter, sans-serif',
            height: '32px',
            transition: 'all 0.15s ease',
          }}
          onMouseEnter={e => {
            e.currentTarget.style.background = 'hsl(var(--accent) / .08)'
            e.currentTarget.style.borderColor = 'hsl(var(--accent))'
          }}
          onMouseLeave={e => {
            e.currentTarget.style.background = 'transparent'
            e.currentTarget.style.borderColor = 'hsl(var(--accent) / .4)'
          }}
        >
          <FileText size={13} />
          <span>View MoM Page</span>
        </button>
 
        <button
          onClick={handlePdf}
          disabled={pdfStatus === 'loading'}
          style={{
            display: 'inline-flex',
            alignItems: 'center',
            gap: '6px',
            background: 'transparent',
            border: `1.5px solid ${pdfStatus === 'error' ? 'hsl(var(--destructive))' : pdfStatus === 'success' ? 'hsl(var(--success))' : 'hsl(var(--pencil) / .3)'}`,
            borderRadius: '6px',
            padding: '.35rem .75rem',
            fontSize: '.76rem',
            fontWeight: 600,
            color: pdfStatus === 'error' ? 'hsl(var(--destructive))' : pdfStatus === 'success' ? 'hsl(var(--success))' : 'hsl(var(--ink-soft))',
            cursor: pdfStatus === 'loading' ? 'not-allowed' : 'pointer',
            fontFamily: 'Inter, sans-serif',
            height: '32px',
            transition: 'all 0.15s ease',
          }}
          onMouseEnter={e => {
            if (pdfStatus === 'idle') {
              e.currentTarget.style.background = 'hsl(var(--muted))'
              e.currentTarget.style.borderColor = 'hsl(var(--pencil) / .6)'
            }
          }}
          onMouseLeave={e => {
            if (pdfStatus === 'idle') {
              e.currentTarget.style.background = 'transparent'
              e.currentTarget.style.borderColor = 'hsl(var(--pencil) / .3)'
            }
          }}
        >
          {pdfStatus === 'loading' ? (
            <Loader size={13} className="spin" />
          ) : pdfStatus === 'success' ? (
            <Check size={13} style={{ color: 'hsl(var(--success))' }} />
          ) : (
            <FileText size={13} />
          )}
          <span>
            {pdfStatus === 'loading'
              ? 'Downloading…'
              : pdfStatus === 'success'
              ? 'Downloaded!'
              : pdfStatus === 'error'
              ? 'Failed'
              : 'Download PDF'}
          </span>
        </button>
      </div>

      {/* Title */}
      {mom.title && (
        <div style={{
          fontFamily: 'Inter, sans-serif',
          fontSize: '.95rem',
          fontWeight: 700,
          color: 'hsl(var(--ink))',
          letterSpacing: '-.01em',
          lineHeight: 1.3,
        }}>
          {mom.title}
        </div>
      )}

      {/* Meta row */}
      {(mom.date || (mom.participants && mom.participants.length > 0)) && (
        <div style={{
          display: 'flex', gap: '8px', flexWrap: 'wrap',
          fontSize: '.7rem', color: 'hsl(var(--pencil))',
          fontFamily: 'Inter, sans-serif',
        }}>
          {mom.date && <span>📅 {mom.date}</span>}
          {mom.participants && mom.participants.length > 0 && (
            <span>👥 {mom.participants.join(', ')}</span>
          )}
        </div>
      )}

      {/* Introduction */}
      {mom.introduction && (
        <div style={{
          background: 'linear-gradient(135deg, hsl(var(--accent) / .06), hsl(var(--accent) / .02))',
          border: '1px solid hsl(var(--accent) / .2)',
          borderLeft: '3px solid hsl(var(--accent))',
          borderRadius: '8px', padding: '.75rem 1rem',
        }}>
          <div style={{
            fontSize: '.62rem', fontWeight: 700, color: 'hsl(var(--accent))',
            textTransform: 'uppercase', letterSpacing: '.08em',
            marginBottom: '6px', fontFamily: 'Inter, sans-serif',
            display: 'flex', alignItems: 'center', gap: '4px',
          }}>
            <FileText size={10} /> Introduction
          </div>
          <p style={{
            fontSize: '.83rem', color: 'hsl(var(--ink-soft))',
            fontFamily: 'Inter, sans-serif', lineHeight: 1.65, margin: 0,
          }}>
            {mom.introduction}
          </p>
        </div>
      )}

      {/* Points discussed */}
      {mom.points_discussed && mom.points_discussed.length > 0 && (
        <div style={{
          background: 'hsl(var(--card))',
          border: '1px solid hsl(var(--border) / .25)',
          borderLeft: '3px solid hsl(280,70%,60%)',
          borderRadius: '8px', padding: '.75rem 1rem',
        }}>
          <div style={{
            fontSize: '.62rem', fontWeight: 700, color: 'hsl(280,70%,50%)',
            textTransform: 'uppercase', letterSpacing: '.08em',
            marginBottom: '8px', fontFamily: 'Inter, sans-serif',
            display: 'flex', alignItems: 'center', gap: '4px',
          }}>
            <ListChecks size={10} /> Points Discussed
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '5px' }}>
            {mom.points_discussed.map((pt, i) => (
              <div key={i} style={{
                fontSize: '.82rem', color: 'hsl(var(--ink-soft))',
                paddingLeft: '.9rem', position: 'relative',
                lineHeight: 1.55, fontFamily: 'Inter, sans-serif',
              }}>
                <span style={{ position: 'absolute', left: 0, color: 'hsl(280,70%,50%)', fontWeight: 700 }}>•</span>
                {pt}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Action items */}
      {mom.action_items && mom.action_items.length > 0 && (
        <div style={{
          background: 'hsl(var(--card))',
          border: '1px solid hsl(var(--success) / .2)',
          borderLeft: '3px solid hsl(var(--success))',
          borderRadius: '8px', padding: '.75rem 1rem',
        }}>
          <div style={{
            fontSize: '.62rem', fontWeight: 700, color: 'hsl(var(--success))',
            textTransform: 'uppercase', letterSpacing: '.08em',
            marginBottom: '8px', fontFamily: 'Inter, sans-serif',
            display: 'flex', alignItems: 'center', gap: '4px',
          }}>
            <CheckCircle size={10} /> Action Items
          </div>
          <div style={{ display: 'flex', flexDirection: 'column', gap: '5px' }}>
            {mom.action_items.map((ai, i) => (
              <div key={i} style={{
                fontSize: '.8rem', color: 'hsl(var(--ink-soft))',
                lineHeight: 1.55, fontFamily: 'Inter, sans-serif',
                display: 'flex', gap: '6px', alignItems: 'flex-start',
              }}>
                <span style={{ color: 'hsl(var(--success))', fontSize: '.9rem', flexShrink: 0 }}>☐</span>
                <span>
                  {ai.task}
                  {ai.owner && ai.owner !== 'Unassigned' && (
                    <span style={{ color: 'hsl(var(--pencil))', fontSize: '.72rem', marginLeft: '4px' }}>— {ai.owner}</span>
                  )}
                  {ai.deadline && (
                    <span style={{ color: 'hsl(var(--pencil))', fontSize: '.72rem', marginLeft: '4px' }}>({ai.deadline})</span>
                  )}
                </span>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Conclusion */}
      {mom.conclusion && (
        <div style={{
          background: 'hsl(var(--muted) / .5)',
          border: '1px solid hsl(var(--border) / .2)',
          borderRadius: '8px', padding: '.75rem 1rem',
        }}>
          <div style={{
            fontSize: '.62rem', fontWeight: 700, color: 'hsl(var(--pencil))',
            textTransform: 'uppercase', letterSpacing: '.08em',
            marginBottom: '6px', fontFamily: 'Inter, sans-serif',
          }}>
            Conclusion
          </div>
          <p style={{
            fontSize: '.82rem', color: 'hsl(var(--ink-soft))',
            fontFamily: 'Inter, sans-serif', lineHeight: 1.65, margin: 0,
          }}>
            {mom.conclusion}
          </p>
        </div>
      )}
    </div>
  )
}

// ── Action Items renderer (General + Speaker sections) ────────
// ── Action Items renderer (Improved) ───────────────────────────
function ActionItemsRenderer({ items }: { items: string[] }) {
  if (!items || items.length === 0) return null

  type Section = {
    header: string
    items: string[]
  }

  let sections: Section[] = []

  // -------------------------------------------------------
  // Try parsing JSON first
  // -------------------------------------------------------
  if (
    items.length === 1 &&
    (items[0].trim().startsWith("{") || items[0].trim().startsWith("["))
  ) {
    try {
      const json = JSON.parse(items[0])

      if (json.general_action_items?.length) {
        sections.push({
          header: "General Action Items",
          items: json.general_action_items,
        })
      }

      if (json.speaker_action_items) {
        Object.entries(json.speaker_action_items).forEach(([speaker, value]) => {
          sections.push({
            header: speaker,
            items: value as string[],
          })
        })
      }
    } catch {
      // Ignore and continue with normal parsing
    }
  }

  // -------------------------------------------------------
  // Normal text parser
  // -------------------------------------------------------
  if (sections.length === 0) {
    let current: Section = {
      header: "General Action Items",
      items: [],
    }

    sections.push(current)

    for (const raw of items) {
      const line = raw.trim()

      if (!line) continue

      const cleaned = line
        .replace(/^#+\s*/, "")
        .replace(/:$/, "")

      const isBullet =
        /^[-*•]\s+/.test(line) ||
        /^\d+\.\s+/.test(line)

      if (!isBullet) {
        current = {
          header: cleaned,
          items: [],
        }
        sections.push(current)
        continue
      }

      current.items.push(
        line
          .replace(/^[-*•]\s*/, "")
          .replace(/^\d+\.\s*/, "")
          .trim()
      )
    }

    sections = sections.filter(s => s.items.length)
  }

  // -------------------------------------------------------
  // Render
  // -------------------------------------------------------

  return (
    <div style={{ display: "flex", flexDirection: "column", gap: "18px" }}>
      {sections.map((section, sectionIndex) => {
        const isGeneral = /general/i.test(section.header)

        return (
          <div key={sectionIndex}>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: "8px",
                marginBottom: "10px",
                paddingBottom: "6px",
                borderBottom: "1px solid hsl(var(--border) / .25)",

                fontSize: ".70rem",
                fontWeight: 700,
                textTransform: "uppercase",
                letterSpacing: ".08em",

                color: isGeneral
                  ? "hsl(var(--accent))"
                  : "hsl(var(--ink))",
              }}
            >
              {!isGeneral && (
                <span
                  style={{
                    width: 18,
                    height: 18,
                    borderRadius: "50%",
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",

                    background: `hsl(${(sectionIndex * 137) % 360},70%,90%)`,
                    color: `hsl(${(sectionIndex * 137) % 360},70%,35%)`,

                    fontSize: ".62rem",
                    fontWeight: 700,
                  }}
                >
                  {section.header.charAt(0).toUpperCase()}
                </span>
              )}


              <MarkdownContent content={section.header} />
            </div>

            {section.items.map((item, i) => (
              <div
                key={i}
                style={{
                  display: "flex",
                  alignItems: "flex-start",
                  gap: "8px",
                  marginBottom: "8px",
                }}
              >
                <span
                  style={{
                    color: isGeneral
                      ? "hsl(var(--accent))"
                      : "hsl(var(--success))",
                    fontSize: ".9rem",
                    marginTop: "2px",
                    flexShrink: 0,
                  }}
                >
                  ☐
                </span>

                <div style={{ flex: 1 }}>
                  <MarkdownContent content={item} />
                </div>
              </div>
            ))}
          </div>
        )
      })}
    </div>
  )
}
// ── Main Component ────────────────────────────────────────────
export default function AIChatPanel({
  recordingId,
  summary,
  shortSummary,
  detailedSummary,
  keyPoints,
  actionItems,
  speakerSummary,
  momData,
  isOpen,
  onToggle,
  isGenerating = false,
  isGeneratingMom = false,
  onGenerateInsights,
  isGeneratingInsights = false,
}: Props) {
  const [summaryTab, setSummaryTab] = useState<'short' | 'detailed' | 'speaker'>('short')
  const [activeView, setActiveView] = useState<'mom' | 'insights'>('mom')

  const resolvedShort = shortSummary || summary || ''
  const resolvedDetailed = detailedSummary || ''

  const hasMom = momData && (momData.title || momData.introduction || (momData.points_discussed && momData.points_discussed.length > 0))
  const hasInsights = resolvedShort || resolvedDetailed || keyPoints?.length || actionItems?.length || (speakerSummary && Object.keys(speakerSummary).length > 0)

  const showGeneratingSkeleton = isGenerating && !hasInsights
  const showMomGenerating = isGeneratingMom && !hasMom

  /* ── Collapsed strip */
  if (!isOpen) {
    return (
      <div style={{
        display: 'flex', flexDirection: 'column', alignItems: 'center',
        paddingTop: '.75rem',
        background: 'hsl(var(--card))',
        borderLeft: '1.5px solid hsl(var(--border) / .2)',
      }}>
        <button className="icon-btn" onClick={onToggle} title="Open AI & MoM Panel" style={{ marginBottom: '12px' }}>
          <ChevronLeft size={16} />
        </button>
        <div style={{
          width: '34px', height: '34px', borderRadius: '10px',
          background: 'linear-gradient(135deg, hsl(var(--accent) / .15), hsl(var(--accent) / .05))',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          border: '1.5px solid hsl(var(--accent) / .3)',
          boxShadow: '0 0 12px hsl(var(--accent) / .1)',
        }}>
          <ClipboardList size={17} style={{ color: 'hsl(var(--accent))' }} />
        </div>
        {(hasMom || hasInsights || isGenerating || isGeneratingMom) && (
          <div style={{
            marginTop: '10px',
            width: '8px', height: '8px',
            borderRadius: '50%',
            background: (isGenerating || isGeneratingMom) ? 'hsl(var(--accent))' : 'hsl(var(--success))',
            boxShadow: (isGenerating || isGeneratingMom) ? '0 0 8px hsl(var(--accent) / .6)' : '0 0 8px hsl(var(--success) / .6)',
          }} className="animate-pulse-rec" />
        )}
      </div>
    )
  }

  return (
    <div style={{
      display: 'flex', flexDirection: 'column', height: '100%',
      background: 'hsl(var(--card))',
      borderLeft: '1.5px solid hsl(var(--border) / .2)',
      overflow: 'hidden',
    }}>
      {/* Header */}
      <div style={{
        display: 'flex', alignItems: 'center', gap: '10px',
        padding: '.9rem 1rem',
        borderBottom: '1.5px solid hsl(var(--border) / .2)',
        background: 'linear-gradient(180deg, hsl(var(--card)) 0%, hsl(var(--card) / .9) 100%)',
        backdropFilter: 'blur(8px)',
        flexShrink: 0,
        minHeight: '58px',
      }}>
        <div style={{
          width: '32px', height: '32px', borderRadius: '9px', flexShrink: 0,
          background: 'linear-gradient(135deg, hsl(var(--accent) / .18), hsl(var(--accent) / .06))',
          display: 'flex', alignItems: 'center', justifyContent: 'center',
          border: '1.5px solid hsl(var(--accent) / .35)',
          boxShadow: '0 0 14px hsl(var(--accent) / .12)',
        }}>
          <ClipboardList size={16} style={{ color: 'hsl(var(--accent))' }} />
        </div>
        <div style={{ flex: 1, minWidth: 0 }}>
          <div style={{
            fontSize: '.88rem', fontWeight: 700, fontFamily: 'Inter, sans-serif',
            color: 'hsl(var(--ink))', lineHeight: 1.2,
            display: 'flex', alignItems: 'center', gap: '6px',
          }}>
            AI & MoM Panel
            <LocalAIBadge />
          </div>
          <div style={{ fontSize: '.65rem', color: 'hsl(var(--pencil))', fontFamily: 'Inter, sans-serif', marginTop: '2px' }}>
            Powered by Qwen AI · Fully offline
          </div>
        </div>
        <button className="icon-btn" onClick={onToggle} title="Collapse panel" style={{ width: '30px', height: '30px', flexShrink: 0 }}>
          <ChevronRight size={14} />
        </button>
      </div>

      {/* View selector tabs — only when recording is selected */}
      {recordingId && (
        <div style={{
          display: 'flex', gap: 0,
          borderBottom: '1px solid hsl(var(--border) / .18)',
          padding: '0 .75rem',
          flexShrink: 0,
          background: 'hsl(var(--paper) / .3)',
        }}>
          <button
            onClick={() => setActiveView('mom')}
            style={{
              background: 'none', border: 'none', cursor: 'pointer',
              padding: '.55rem .75rem',
              fontSize: '.72rem', fontWeight: 700,
              fontFamily: 'Inter, sans-serif',
              textTransform: 'uppercase', letterSpacing: '.07em',
              color: activeView === 'mom' ? 'hsl(var(--accent))' : 'hsl(var(--pencil))',
              borderBottom: activeView === 'mom' ? '2px solid hsl(var(--accent))' : '2px solid transparent',
              marginBottom: '-1px', transition: 'color .18s',
              display: 'flex', alignItems: 'center', gap: '5px',
            }}
          >
            <ClipboardList size={10} /> MoM
            {(hasMom) && <span style={{
              width: '6px', height: '6px', borderRadius: '50%',
              background: 'hsl(var(--success))', flexShrink: 0,
            }} />}
          </button>
          <button
            onClick={() => setActiveView('insights')}
            style={{
              background: 'none', border: 'none', cursor: 'pointer',
              padding: '.55rem .75rem',
              fontSize: '.72rem', fontWeight: 700,
              fontFamily: 'Inter, sans-serif',
              textTransform: 'uppercase', letterSpacing: '.07em',
              color: activeView === 'insights' ? 'hsl(var(--accent))' : 'hsl(var(--pencil))',
              borderBottom: activeView === 'insights' ? '2px solid hsl(var(--accent))' : '2px solid transparent',
              marginBottom: '-1px', transition: 'color .18s',
              display: 'flex', alignItems: 'center', gap: '5px',
            }}
          >
            <Sparkles size={10} /> AI Insights
            {hasInsights && <span style={{
              width: '6px', height: '6px', borderRadius: '50%',
              background: 'hsl(var(--success))', flexShrink: 0,
            }} />}
          </button>
        </div>
      )}

      {/* Content area */}
      <div style={{ flex: 1, overflowY: 'auto', minHeight: 0 }}>

        {/* No recording selected */}
        {!recordingId && (
          <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', padding: '2rem', gap: '14px', textAlign: 'center' }}>
            <div style={{
              width: '56px', height: '56px', borderRadius: '16px',
              background: 'linear-gradient(135deg, hsl(var(--accent) / .12), hsl(var(--accent) / .04))',
              border: '1.5px solid hsl(var(--accent) / .25)',
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              boxShadow: '0 0 20px hsl(var(--accent) / .08)',
            }}>
              <ClipboardList size={24} style={{ color: 'hsl(var(--accent))' }} className="animate-float" />
            </div>
            <div>
              <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '.88rem', color: 'hsl(var(--ink))', fontWeight: 600, marginBottom: '.3rem' }}>
                AI & MoM Panel
              </p>
              <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '.78rem', color: 'hsl(var(--pencil))', lineHeight: 1.5, maxWidth: '380px', margin: '0 auto' }}>
                Process a recording to see the auto-generated Minutes of Meeting and AI insights
              </p>
            </div>
          </div>
        )}

        {/* ── MoM Tab ── */}
        {recordingId && activeView === 'mom' && (
          <>
            {/* MoM generating skeleton */}
            {showMomGenerating && (
              <AIGeneratingSkeleton messages={MOM_GENERATING_MESSAGES} />
            )}

            {/* MoM ready */}
            {!showMomGenerating && hasMom && (
              <MomDisplay mom={momData!} recordingId={recordingId} />
            )}

            {/* No MoM yet (pipeline done, MoM failed or not yet run) */}
            {!showMomGenerating && !hasMom && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', padding: '2rem', gap: '14px', textAlign: 'center' }}>
                <div style={{
                  width: '56px', height: '56px', borderRadius: '16px',
                  background: 'linear-gradient(135deg, hsl(var(--muted) / .3), hsl(var(--muted) / .1))',
                  border: '1.5px solid hsl(var(--border) / .3)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                }}>
                  <ClipboardList size={24} style={{ color: 'hsl(var(--pencil))' }} />
                </div>
                <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '.82rem', color: 'hsl(var(--pencil))', lineHeight: 1.5, maxWidth: '280px', margin: '0 auto' }}>
                  Minutes of Meeting will appear here after processing completes
                </p>
              </div>
            )}
          </>
        )}

        {/* ── AI Insights Tab ── */}
        {recordingId && activeView === 'insights' && (
          <>
            {/* Generating skeleton for AI insights */}
            {showGeneratingSkeleton && (
              <AIGeneratingSkeleton />
            )}

            {/* Generate AI Insights button — shown when no insights yet */}
            {!showGeneratingSkeleton && !hasInsights && (
              <div style={{
                display: 'flex', flexDirection: 'column', alignItems: 'center',
                justifyContent: 'center', height: '100%',
                padding: '2rem', gap: '16px', textAlign: 'center',
              }}>
                <div style={{
                  width: '56px', height: '56px', borderRadius: '16px',
                  background: 'linear-gradient(135deg, hsl(var(--accent) / .12), hsl(var(--accent) / .04))',
                  border: '1.5px solid hsl(var(--accent) / .25)',
                  display: 'flex', alignItems: 'center', justifyContent: 'center',
                  boxShadow: '0 0 20px hsl(var(--accent) / .08)',
                }}>
                  <Sparkles size={24} style={{ color: 'hsl(var(--accent))' }} className="animate-float" />
                </div>
                <div>
                  <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '.88rem', color: 'hsl(var(--ink))', fontWeight: 600, marginBottom: '.3rem' }}>
                    AI Insights
                  </p>
                  <p style={{ fontFamily: 'Inter, sans-serif', fontSize: '.78rem', color: 'hsl(var(--pencil))', lineHeight: 1.5, maxWidth: '240px', margin: '0 auto .75rem' }}>
                    Generate a summary, key points, and action items from this recording
                  </p>
                </div>
                {onGenerateInsights && (
                  <button
                    id="generate-insights-btn"
                    onClick={() => onGenerateInsights(['short_summary', 'detailed_summary', 'key_points', 'action_items'])}
                    disabled={isGeneratingInsights}
                    style={{
                      display: 'flex', alignItems: 'center', gap: '8px',
                      padding: '.65rem 1.4rem',
                      background: isGeneratingInsights
                        ? 'hsl(var(--muted))'
                        : 'linear-gradient(135deg, hsl(var(--accent)), hsl(var(--accent) / .8))',
                      color: isGeneratingInsights ? 'hsl(var(--pencil))' : 'white',
                      border: 'none', borderRadius: '10px',
                      fontSize: '.85rem', fontWeight: 700,
                      fontFamily: 'Inter, sans-serif',
                      cursor: isGeneratingInsights ? 'not-allowed' : 'pointer',
                      boxShadow: isGeneratingInsights ? 'none' : '0 4px 14px hsl(var(--accent) / .3)',
                      transition: 'all .2s',
                    }}
                  >
                    {isGeneratingInsights
                      ? <><Loader size={15} className="spin" /> Generating…</>
                      : <><Zap size={15} /> Generate AI Insights</>
                    }
                  </button>
                )}
              </div>
            )}

            {/* AI insights loaded — show full panel */}
            {hasInsights && (
              <>
                {/* Re-generate button strip at top when insights already exist */}
                {onGenerateInsights && (
                  <div style={{
                    padding: '.55rem 1rem',
                    borderBottom: '1px solid hsl(var(--border) / .15)',
                    display: 'flex', justifyContent: 'flex-end',
                    background: 'hsl(var(--paper) / .3)',
                    flexShrink: 0,
                  }}>
                    <button
                      onClick={() => onGenerateInsights(['short_summary', 'detailed_summary', 'key_points', 'action_items'])}
                      disabled={isGeneratingInsights}
                      style={{
                        display: 'flex', alignItems: 'center', gap: '5px',
                        padding: '.3rem .7rem',
                        background: 'none',
                        color: 'hsl(var(--accent))',
                        border: '1.5px solid hsl(var(--accent) / .3)',
                        borderRadius: '7px',
                        fontSize: '.7rem', fontWeight: 700,
                        fontFamily: 'Inter, sans-serif',
                        cursor: isGeneratingInsights ? 'not-allowed' : 'pointer',
                        opacity: isGeneratingInsights ? 0.5 : 1,
                        transition: 'all .2s',
                      }}
                    >
                      {isGeneratingInsights
                        ? <><Loader size={11} className="spin" /> Generating…</>
                        : <><Zap size={11} /> Regenerate</>
                      }
                    </button>
                  </div>
                )}

                {/* Tabbed Summary Card */}
                {(resolvedShort || resolvedDetailed || (speakerSummary && Object.keys(speakerSummary).length > 0)) && (
                  <div style={{
                    borderBottom: '1.5px solid hsl(var(--border) / .2)',
                    background: 'hsl(var(--paper) / .4)',
                  }}>
                    {/* Tab strip */}
                    <div style={{ display: 'flex', gap: 0, borderBottom: '1px solid hsl(var(--border) / .18)', padding: '0 .75rem' }}>
                      {([
                        ...(resolvedShort ? [{ id: 'short', label: 'Short', icon: <Sparkles size={10} /> }] : []),
                        ...(resolvedDetailed ? [{ id: 'detailed', label: 'Detailed', icon: <FileText size={10} /> }] : []),
                        ...(speakerSummary && Object.keys(speakerSummary).length > 0
                          ? [{ id: 'speaker', label: 'Speakers', icon: <Users size={10} /> }]
                          : []),
                      ] as const).map((tab) => (
                        <button
                          key={tab.id}
                          onClick={() => setSummaryTab(tab.id as 'short' | 'detailed' | 'speaker')}
                          style={{
                            background: 'none', border: 'none', cursor: 'pointer',
                            padding: '.55rem .75rem',
                            fontSize: '.72rem', fontWeight: 700,
                            fontFamily: 'Inter, sans-serif',
                            textTransform: 'uppercase', letterSpacing: '.07em',
                            color: summaryTab === tab.id ? 'hsl(var(--accent))' : 'hsl(var(--pencil))',
                            borderBottom: summaryTab === tab.id ? '2px solid hsl(var(--accent))' : '2px solid transparent',
                            marginBottom: '-1px', transition: 'color .18s',
                            display: 'flex', alignItems: 'center', gap: '5px',
                          }}
                        >
                          {tab.icon} {tab.label}
                        </button>
                      ))}
                    </div>

                    {/* Short summary tab */}
                    {summaryTab === 'short' && resolvedShort && (
                      <div style={{ padding: '.85rem 1rem' }}>
                        <div style={{
                          background: 'linear-gradient(135deg, hsl(var(--accent) / .06), hsl(var(--accent) / .02))',
                          border: '1px solid hsl(var(--accent) / .2)',
                          borderLeft: '3px solid hsl(var(--accent))',
                          borderRadius: '8px', padding: '.8rem 1rem',
                        }}>
                          <p style={{
                            fontSize: '.85rem', color: 'hsl(var(--ink-soft))',
                            fontFamily: 'Inter, sans-serif', lineHeight: 1.7, margin: 0,
                          }}>
                            {resolvedShort}
                          </p>
                        </div>
                        <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '4px' }}>
                          <CopyButton text={resolvedShort} />
                        </div>
                      </div>
                    )}

                    {/* Detailed summary tab — full markdown */}
                    {summaryTab === 'detailed' && (
                      <div style={{ padding: '.85rem 1rem' }}>
                        {resolvedDetailed ? (
                          <>
                            <MarkdownContent content={resolvedDetailed} />
                            <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '6px' }}>
                              <CopyButton text={resolvedDetailed} />
                            </div>
                          </>
                        ) : (
                          <p style={{ fontSize: '.82rem', color: 'hsl(var(--pencil))', fontFamily: 'Inter, sans-serif', fontStyle: 'italic', margin: 0, textAlign: 'center', padding: '1rem 0' }}>
                            Detailed summary available for newly processed recordings.
                          </p>
                        )}
                      </div>
                    )}

                    {/* Speaker summary tab */}
                    {summaryTab === 'speaker' && speakerSummary && (
                      <div style={{ padding: '.85rem 1rem', display: 'flex', flexDirection: 'column', gap: '14px' }}>
                        {Object.entries(speakerSummary).map(([speaker, spData], idx) => (
                          <div
                            key={speaker}
                            style={{
                              background: 'hsl(var(--card))',
                              border: '1.5px solid hsl(var(--border) / .25)',
                              borderRadius: '8px', padding: '.8rem 1rem',
                              display: 'flex', flexDirection: 'column', gap: '8px',
                            }}
                          >
                            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
                              <div style={{
                                width: '22px', height: '22px', borderRadius: '50%',
                                background: `hsl(${(idx * 137) % 360}, 65%, 50% / .15)`,
                                color: `hsl(${(idx * 137) % 360}, 65%, 50%)`,
                                display: 'flex', alignItems: 'center', justifyContent: 'center',
                                fontSize: '.65rem', fontWeight: 700, fontFamily: 'Inter, sans-serif',
                              }}>
                                {speaker.slice(0, 2).toUpperCase()}
                              </div>
                              <span style={{ fontWeight: 700, fontSize: '.85rem', color: 'hsl(var(--ink))', fontFamily: 'Inter, sans-serif' }}>
                                {speaker}
                              </span>
                            </div>

                            {spData.summary && (
                              <p style={{ fontSize: '.8rem', color: 'hsl(var(--ink-soft))', margin: 0, lineHeight: 1.6, fontFamily: 'Inter, sans-serif' }}>
                                {spData.summary}
                              </p>
                            )}

                            {spData.key_points && spData.key_points.length > 0 && (
                              <div style={{ marginTop: '4px' }}>
                                <div style={{ fontSize: '.65rem', fontWeight: 750, color: 'hsl(var(--pencil))', textTransform: 'uppercase', letterSpacing: '.04em', marginBottom: '4px', fontFamily: 'Inter, sans-serif' }}>
                                  Key Points
                                </div>
                                {spData.key_points.map((kp, kIdx) => (
                                  <div key={kIdx} style={{ fontSize: '.78rem', color: 'hsl(var(--ink-soft))', paddingLeft: '.75rem', position: 'relative', marginBottom: '2px', lineHeight: 1.4, fontFamily: 'Inter, sans-serif' }}>
                                    <span style={{ position: 'absolute', left: 0, color: 'hsl(var(--accent))' }}>•</span>
                                    {kp}
                                  </div>
                                ))}
                              </div>
                            )}

                            {spData.action_items && spData.action_items.length > 0 && (
                              <div style={{ marginTop: '4px' }}>
                                <div style={{ fontSize: '.65rem', fontWeight: 750, color: 'hsl(var(--pencil))', textTransform: 'uppercase', letterSpacing: '.04em', marginBottom: '4px', fontFamily: 'Inter, sans-serif' }}>
                                  Action Items
                                </div>
                                {spData.action_items.map((ai, aIdx) => (
                                  <div key={aIdx} style={{ fontSize: '.78rem', color: 'hsl(var(--ink-soft))', paddingLeft: '.75rem', position: 'relative', marginBottom: '2px', lineHeight: 1.4, fontFamily: 'Inter, sans-serif' }}>
                                    <span style={{ position: 'absolute', left: 0, color: 'hsl(var(--success))' }}>•</span>
                                    {ai}
                                  </div>
                                ))}
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    )}
                  </div>
                )}

                {/* Key points + action items */}
                {(keyPoints?.length || actionItems?.length) ? (
                  <div style={{ padding: '.9rem', display: 'flex', flexDirection: 'column', gap: '10px' }}>

                    {keyPoints && keyPoints.length > 0 && (
                      <div className="animate-slide-up" style={{
                        padding: '.9rem 1rem',
                        background: 'hsl(var(--card))',
                        borderRadius: '10px',
                        border: '1px solid hsl(var(--success) / .2)',
                        borderLeft: '3px solid hsl(var(--success))',
                      }}>
                        <div style={{
                          fontSize: '.68rem', fontWeight: 700,
                          color: 'hsl(var(--success))',
                          textTransform: 'uppercase', letterSpacing: '.09em',
                          marginBottom: '8px',
                          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                          fontFamily: 'Inter, sans-serif',
                        }}>
                          <span style={{ display: 'flex', alignItems: 'center', gap: '5px' }}>
                            <FileText size={11} /> Key Points
                          </span>
                          <span style={{ background: 'hsl(var(--success) / .1)', padding: '.08rem .4rem', borderRadius: '999px', fontSize: '.62rem' }}>
                            {keyPoints.length}
                          </span>
                        </div>
                        {keyPoints.map((k, i) => (
                          <div key={i} style={{
                            fontSize: '.83rem', color: 'hsl(var(--ink-soft))',
                            marginBottom: '5px', paddingLeft: '.9rem', position: 'relative',
                            lineHeight: 1.65, fontFamily: 'Inter, sans-serif',
                          }}>
                            <span style={{ position: 'absolute', left: 0, color: 'hsl(var(--success))', fontWeight: 700 }}>•</span>

                            <MarkdownContent content={k} />

                          </div>
                        ))}
                      </div>
                    )}

                    {actionItems && actionItems.length > 0 && (
                      <div className="animate-slide-up" style={{
                        padding: '.9rem 1rem',
                        background: 'hsl(var(--card))',
                        borderRadius: '10px',
                        border: '1px solid hsl(var(--accent) / .2)',
                        borderLeft: '3px solid hsl(var(--accent))',
                      }}>
                        <div style={{
                          fontSize: '.68rem', fontWeight: 700,
                          color: 'hsl(var(--accent))',
                          textTransform: 'uppercase', letterSpacing: '.09em',
                          marginBottom: '10px',
                          display: 'flex', alignItems: 'center', justifyContent: 'space-between',
                          fontFamily: 'Inter, sans-serif',
                        }}>
                          <span style={{ display: 'flex', alignItems: 'center', gap: '5px' }}>
                            <ListChecks size={11} /> Action Items
                          </span>
                        </div>
                        <ActionItemsRenderer items={actionItems} />
                      </div>
                    )}

                  </div>
                ) : null}
              </>
            )}
          </>
        )}

      </div>{/* end scroll container */}

      {/* Footer */}
      <div style={{
        padding: '.55rem 1rem',
        borderTop: '1px solid hsl(var(--border) / .15)',
        display: 'flex', alignItems: 'center', gap: '6px',
        flexShrink: 0,
        background: 'hsl(var(--card))',
      }}>
        <div style={{
          width: '7px', height: '7px', borderRadius: '50%',
          background: 'hsl(var(--success))',
          boxShadow: '0 0 6px hsl(var(--success) / .6)',
          flexShrink: 0,
        }} />
        <span style={{ fontSize: '.65rem', color: 'hsl(var(--pencil))', fontFamily: 'Inter, sans-serif' }}>
          Qwen-AI · Running locally · No internet required
        </span>
      </div>
    </div>
  )
}
