# -*- mode: python ; coding: utf-8 -*-
"""
PyInstaller spec for the FastAPI backend.
Build: pyinstaller backend.spec --distpath Application/ --workpath build/backend_work
"""
import sys
from pathlib import Path
from PyInstaller.utils.hooks import copy_metadata, collect_submodules, collect_data_files

block_cipher = None
# SPECPATH is always the directory that contains this .spec file (i.e. tools/).
# The project root is one level up.
ROOT = Path(SPECPATH).parent
BACKEND_DIR = ROOT / "backend"

# ---------------------------------------------------------------------------
# copy_metadata() bundles the .dist-info directory so that
# importlib.metadata.version("<pkg>") works at runtime inside the frozen exe.
#
# This list was generated by tracing importlib.metadata.version() calls during
# import of: transformers, torchaudio, whisperx, pyannote.audio
#
# Packages that are NOT installed in the venv are silently skipped.
# ---------------------------------------------------------------------------
def safe_copy_metadata(pkg):
    """Return copy_metadata result, or [] if the package is not installed."""
    try:
        return copy_metadata(pkg)
    except Exception:
        return []

metadata_packages = [
    # Core ML / transformers ecosystem
    "torch", "torchaudio", "torchvision", "transformers", "tokenizers",
    "accelerate", "bitsandbytes", "safetensors", "huggingface-hub",
    # Whisper / transcription
    "faster_whisper", "whisperx", "ctranslate2",
    # Pyannote
    "pyannote-audio", "pyannote-core", "pyannote-database", "pyannote-pipeline",
    # Audio
    "librosa", "soundfile", "tqdm", "torchcodec",
    # NLP / utilities
    "sentencepiece", "nltk", "scipy", "numpy", "pandas", "scikit-learn",
    "regex", "requests", "packaging", "filelock", "pyyaml", "Pillow",
    # Web / API
    "fastapi", "uvicorn", "aiohttp", "pydantic", "Jinja2",
    "httpx", "aiofiles",
    # Others probed by pyannote/speechbrain
    "onnxruntime", "psutil", "pygments", "rich", "optree",
    "optimum_quanto", "gammatone", "pesq", "piq", "pystoi",
    "torchmetrics", "pyannote-audio",
    # Additional packages
    "python-pptx", "pptx", "pytesseract", "pypdf",
]

collected_metadata = []
for pkg in metadata_packages:
    collected_metadata += safe_copy_metadata(pkg)


# Automatically collect all package-specific data files (YAML configs, models, assets)
data_packages = [
    "pyannote.audio",
    "whisperx",
    "onnxruntime",
    "speechbrain",
    "pptx",
]
collected_datas = []
for pkg in data_packages:
    try:
        collected_datas += collect_data_files(pkg)
    except Exception as e:
        print(f"WARNING: Failed to collect data files for {pkg}: {e}")

# Automatically collect all submodules of packages with lazy/dynamic imports
submodule_packages = [
    "whisperx",
    "faster_whisper",
    "pyannote",
    "speechbrain",
    "onnxruntime",
]
collected_submodules = []
for pkg in submodule_packages:
    try:
        collected_submodules += collect_submodules(pkg)
    except Exception as e:
        print(f"WARNING: Failed to collect submodules for {pkg}: {e}")

# Helper to bundle the entire package source and resources
def collect_full_package(pkg_name):
    """Return a list of (source_path, dest_dir) to copy the entire package directory."""
    try:
        import importlib
        pkg = importlib.import_module(pkg_name)
        pkg_path = Path(pkg.__path__[0])
        return [(str(pkg_path), pkg_name)]
    except Exception as e:
        print(f"WARNING: Failed to collect full package {pkg_name}: {e}")
        return []

full_copy_packages = [
    "speechbrain",
    "pptx",
    "docx",
    "pypdf",
    "pytesseract",
    "reportlab",
    "fitz",
    "pymupdf",
]
collected_full_packages = []
for pkg in full_copy_packages:
    collected_full_packages += collect_full_package(pkg)

a = Analysis(
    [str(BACKEND_DIR / "main.py")],
    pathex=[str(BACKEND_DIR)],
    binaries=[],
    datas=[
        # Include .env template (actual .env loaded from cwd at runtime)
        (str(BACKEND_DIR / ".env.example"), "."),
        # Bundle .dist-info dirs so importlib.metadata.version() works at runtime
        *collected_metadata,
        # Bundle automatically collected data files
        *collected_datas,
        # Bundle full directories of packages that do dynamic import scanning or resource lookups
        *collected_full_packages,
        # Fallback raw copy of all local backend modules to guarantee import availability
        (str(BACKEND_DIR / "routers"), "routers"),
        (str(BACKEND_DIR / "services"), "services"),
        (str(BACKEND_DIR / "tasks"), "tasks"),
        (str(BACKEND_DIR / "models"), "models"),
        (str(BACKEND_DIR / "utils"), "utils"),
        (str(BACKEND_DIR / "config.py"), "."),
        (str(BACKEND_DIR / "database.py"), "."),
        (str(BACKEND_DIR / "license.py"), "."),
        (str(BACKEND_DIR / "main.py"), "."),
    ],
    hiddenimports=[
        # Automatically collected submodules
        *collected_submodules,
        # FastAPI / Uvicorn
        "uvicorn.logging",
        "uvicorn.loops",
        "uvicorn.loops.auto",
        "uvicorn.loops.asyncio",
        "uvicorn.protocols",
        "uvicorn.protocols.http",
        "uvicorn.protocols.http.auto",
        "uvicorn.protocols.websockets",
        "uvicorn.protocols.websockets.auto",
        "uvicorn.lifespan",
        "uvicorn.lifespan.on",
        "fastapi",
        "fastapi.middleware.cors",
        "fastapi.staticfiles",
        "fastapi.responses",
        # SQLAlchemy / SQLite
        "sqlalchemy.dialects.sqlite",
        "sqlalchemy.dialects.sqlite.aiosqlite",
        "aiosqlite",
        # Auth
        "jose",
        "jose.jwt",
        "passlib.handlers.bcrypt",
        "passlib.handlers.pbkdf2",
        # ML / Audio
        "torch",
        "torchaudio",
        "whisperx",
        "faster_whisper",
        "pyannote.audio",
        "pyannote.audio.pipelines",
        "speechbrain",
        # SpeechBrain submodules required for ECAPA-TDNN speaker embeddings
        "speechbrain.utils",
        "speechbrain.utils.fetching",
        "speechbrain.utils.checkpoints",
        "speechbrain.utils.parameter_transfer",
        "speechbrain.utils.data_utils",
        "speechbrain.inference",
        "speechbrain.inference.speaker",
        "speechbrain.inference.interfaces",
        "speechbrain.nnet",
        "speechbrain.nnet.linear",
        "speechbrain.nnet.normalization",
        "speechbrain.nnet.CNN",
        "speechbrain.nnet.pooling",
        "speechbrain.nnet.attention",
        "speechbrain.nnet.RNN",
        "speechbrain.lobes",
        "speechbrain.lobes.models",
        "speechbrain.lobes.models.ECAPA_TDNN",
        "speechbrain.lobes.features",
        "speechbrain.core",
        "speechbrain.pretrained",
        "onnxruntime",
        "librosa",
        "soundfile",
        "numpy",
        "scipy",
        "sklearn",
        # Transformers — Qwen3 and offline summarization
        "transformers",
        "transformers.models.qwen2",
        "transformers.models.qwen2.modeling_qwen2",
        "transformers.models.qwen2.tokenization_qwen2",
        "transformers.models.qwen2.configuration_qwen2",
        "transformers.models.bart",
        "transformers.pipelines",
        "transformers.pipelines.text_generation",
        # Quantization
        "bitsandbytes",
        "accelerate",
        # HTTP
        "httpx",
        "aiofiles",
        # Crypto
        "cryptography",
        "cryptography.fernet",
        # PDF / Word / PPTX / OCR / Agenda extraction
        "reportlab",
        "reportlab.pdfgen",
        "reportlab.lib",
        "reportlab.platypus",
        "docx",
        "fitz",
        "pptx",
        "pytesseract",
        "pypdf",
        # Extra utils from requirements.txt
        "multipart",
        "dotenv",
        "bcrypt",
        "sentencepiece",
        # App modules — routers
        "routers.auth",
        "routers.voice",
        "routers.audio",
        "routers.history",
        "routers.settings_router",
        "routers.pdf_router",
        "routers.mom_router",
        "routers.prompt_router",
        "routers.dictionary_router",
        "routers.analytics_router",
        "routers.attachments_router",
        "routers.global_context_router",
        "routers.raw_mom_router",
        "routers.dashboard_router",
        "routers.prompt_templates_router",
        # App modules — services
        "services.diarization",
        "services.embedding",
        "services.identification",
        "services.llm",
        "services.ai_provider",
        "services.model_loader",
        "services.record",
        "services.transcription",
        "services.device_utils",
        "services.transcript_normalizer",
        "services.prompt_builder",
        "services.vocab_extractor",
        "services.dictionary_service",
        "services.doc_extractor",
        "services.analytics",
        "services.audio_preprocessing",
        "services.compat",
        "services.prompt_service",
        "services.rag_pipeline",
        "services.text_chunker",
        "services.text_embedding_service",
        "services.vector_store",
        # App modules — utils & core
        "utils.audio_utils",
        "utils.storage",
        "license",
        # App modules — tasks & core
        "tasks.pipeline",
        "tasks.chunk_pipeline",
        "tasks.rereid_pipeline",
        "tasks.upload_chunk_pipeline",
        "database",
        "config",
        "models.user",
        "models.dictionary",
        "models.recording",
        "models.settings",
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        # Only exclude heavy third-party packages that are truly unused.
        # Do NOT exclude stdlib modules — PyTorch imports many of them internally:
        #   torch.distributed     → pdb
        #   torch._dispatch       → unittest.mock
        #   various torch modules → doctest
        "matplotlib",
        "IPython",
        "jupyter",
        "notebook",
        "pytest",
        "sphinx",
    ],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name="backend",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,           # No console window
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name="backend",
)
